# Generated by Django 5.2.7 on 2025-11-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autorized',
            new_name='published',
        ),
    ]
