# Generated by Django 5.2.7 on 2025-11-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_autorized_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
